// <auto-generated />
namespace Covid19.Morocco.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Covid19MoroccoMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Covid19MoroccoMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202003282040157_Covid19MoroccoMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
